version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: human-voice-ai
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    tty: true
    stdin_open: true

  # Uncomment to add a Jupyter Notebook service
  # notebook:
  #   build: .
  #   command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./notebooks:/app/notebooks
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #   depends_on:
  #     - app
